#!/bin/bash

if [[ "$1 " == "clean " ]]
then

make clean

for dir in DFFTPACK bessel H2PROJECT HEPROJECT SINCDVR SINC1D
do
	if [[ -e $dir ]]
	then

	cd $dir
	make clean
	cd ..

	fi

done

else

## PROJECT DIRECTORIES INTERFACE EXPLICITLY WITH MAIN ROUTINES
##                   NOT VICE VERSA.
## MAKE MAIN ROUTINES FIRST, the ones upon which the project dirs
## depend explicitly.  These dependencies are also in the project
## makefiles.

make parameters.o MPI.o proputils.o utils.o blocklanczos.o eigen.o

for dir in DFFTPACK bessel H2PROJECT HEPROJECT SINCDVR SINC1D
do
	if [[ -e $dir ]]
	then

	cd $dir
	make
	cd ..

	fi

done

## NOW MAKE WHOLE PROGRAM

make

fi
